services:
  mailpit:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8025"]
      interval: 1s
      timeout: 10s
      retries: 10
    ports:
      - '${DRAKY_MAILPIT_PORT}:8025'
