services:
  database:
    extends:
      file: ../../services/postgres/services.yml
      service: postgres
  webserver:
    extends:
      file: ../../services/nginx/services.yml
      service: nginx
    depends_on:
      - php
  php:
    extends:
      file: ../../services/php/services.yml
      service: php
  mailpit:
    extends:
      file: ../../services/mailpit/services.yml
      service: mailpit
  redis:
    extends:
      file: ../../services/redis/services.yml
      service: redis
